version: "3.9"
services:
    eureka:
        build: ./eureka-server
        ports:
            - 6660:6660
    
    product:
        build: ./product-service
        depends_on: 
            - eureka
        environment: 
            - EUREKA_HOST=eureka
        ports:
            - 6661:6661
    order:
        build: ./order-service
        depends_on: 
            - eureka
        environment: 
            - EUREKA_HOST=eureka
        ports:
            - 6662:6662
