server:
    port: ${PORT:6662}

spring:
    application: 
        name: order-service

eureka:
    instance:
        hostname: ${HOSTNAME:localhost}
        preferIpAddress: false
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:6660/eureka
