server:
    port: ${PORT:6662}

eureka:
    instance:
        hostname: ${HOSTNAME:localhost}
        preferIpAddress: false
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:6660/eureka
