server:
    port: ${PORT:6661}

spring:
    application: 
        name: product-service

eureka:
    instance:
        hostname: ${HOSTNAME:localhost}
        preferIpAddress: false
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:6660/eureka
logging:
    level:
        root: DEBUG